### ISSUE TITLE
Possible to port to Raspberry Pi Pico W?

### ISSUE THREAD

**Issue by phennessey** [jalenng/unicorn-hat-hd-clock#2]
There's a new 16x16 display that Pimoroni just made called Stellar Unicorn that runs on a Raspberry Pi Pico W, and it has its own graphic library:
https://shop.pimoroni.com/products/space-unicorns?variant=40842632953939

Would your code be able to run on that display? Hoping to see a port!

**Comment by jalenng** [comment]
hey @phennessey, i don't have plans to obtain a Stellar Unicorn and port my code at the moment. feel free to give it a try though, and let me know how it goes!
